# Pre-commit hooks dla projektu OBS Canvas Recording
# Instalacja: uv run pre-commit install
# Uruchomienie: uv run pre-commit run --all-files

repos:
  # Podstawowe formatowanie i sprawdzanie
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=2000']  # Większy limit dla video fixtures
      - id: debug-statements
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Ruff - szybki linter i formatter dla Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Linting (sprawdzanie jakości kodu)
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --extend-ignore=E402]
        types_or: [python, pyi]
      # Formatowanie kodu
      - id: ruff-format
        types_or: [python, pyi]

  # Sprawdzanie typów z mypy (wyłączone na początek)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests]
  #       args: [--ignore-missing-imports, --follow-imports=silent, --no-strict-optional]
  #       # Ignoruj OBS scripting files które nie mają typów
  #       exclude: ^src/obs_integration/obs_script\.py$

  # Sprawdzanie bezpieczeństwa z bandit (wyłączone na początek)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [-r, src/, -ll]  # Low level, pomijaj subprocess calls dla FFmpeg
  #       exclude: tests/

  # Sprawdzanie dokumentacji (wyłączone na początek)
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       args: [--convention=google]
  #       exclude: ^tests/

# Konfiguracja globalna
default_language_version:
  python: python3.12

# Które pliki sprawdzać
files: ^(src/|tests/).*\.py$

# Wykluczenia
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    build/|
    dist/|
    .*\.egg-info/|
    htmlcov/|
    \.pytest_cache/|
    __pycache__/|
    .*\.pyc|
    .*\.pyo|
    tests/fixtures/.*|
    .*test_output.*
  ).*$

# Konfiguracja CI
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
