[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "obs-canvas-recorder"
version = "0.1.0"
description = "Automatic extraction of sources from OBS canvas recordings"
authors = [
    {name = "OBS Canvas Recorder Team"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia :: Video",
]

dependencies = [
    "ffmpeg-python>=0.2.0",
    "pathlib-extensions>=0.1.0",
    "setka-common",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]

[project.urls]
Homepage = "https://github.com/obs-canvas-recorder/obs-canvas-recorder"
Repository = "https://github.com/obs-canvas-recorder/obs-canvas-recorder"
Issues = "https://github.com/obs-canvas-recorder/obs-canvas-recorder/issues"

[project.scripts]
obs-extract = "cli.extract:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=80",
]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "slow: Slow running tests",
    "audio: Tests requiring audio processing libraries",
]

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "ffmpeg.*"
ignore_missing_imports = true 

[dependency-groups]
dev = [
    "ffmpeg-python>=0.2.0",
    "librosa>=0.11.0",
    "numpy>=2.0.2",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-xdist>=3.8.0",
    "scipy>=1.13.1",
    "soundfile>=0.13.1",
]
