[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/*"]

[project]
name = "setka-workspace"
version = "1.0.0"
description = "Setka media processing and automation workspace"
readme = "README.md"
requires-python = ">=3.10"

[tool.uv.sources]
setka-common = { workspace = true }
obsession = { workspace = true }
medusa = { workspace = true }