[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cinemon"
version = "0.1.0"
description = "Blender VSE project preparation and animation tools"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "setka-common",
    "beatrix",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
cinemon-blend-setup = "cinemon.cli.blend_setup:main"
cinemon-generate-config = "cinemon.cli.generate_config:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cinemon"]


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=80",
]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "slow: Slow tests",
]

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*", "*/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
ignore = ["E501", "E402", "N801", "N802", "F401", "F405", "F821", "N803", "N806", "E722"]

[tool.ruff.lint.per-file-ignores]
"blender_addon/**/*.py" = ["ALL"]
"tests/**/*.py" = ["N803", "N806", "E722"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.hatch.metadata]
allow-direct-references = true
